hello:
  links:
    - "db:db"
  build: .
  volumes:
    - .:/app
    - /app/node_modules
  command: node ./src/hello.js
  environment:
    - NODE_ENV=development

autotest:
  links:
    - "db:db"
  build: .
  volumes:
    - ./src:/app/src
    - /app/node_modules
  command: mocha ./src/hello.spec.js --watch
  environment:
    - NODE_ENV=test

test:
  links:
    - "db:db"
  build: .
  volumes:
    - ./src:/app/src
    - /app/node_modules
  command: mocha ./src/hello.spec.js
  environment:
    - NODE_ENV=test

db:
  image: mongo:3
